export interface Property {
  id: string
  slug: string
  name: string
  location: string
  state: string
  type: 'Beach' | 'Desert' | 'Mountain'
  emoji: string
  bedrooms: number
  bathrooms: number
  sleepsMin: number
  sleepsMax: number
  pricePerNight: number
  description: string
  shortDesc: string
  amenities: string[]
  imageUrl: string
  ownerrezUrl: string
  highlights: string[]
  photos: string[]
}

export const properties: Property[] = [
  {
    id: 'casa-grande',
    slug: 'casa-grande',
    name: 'Casa Grandè',
    location: 'Clearwater',
    state: 'FL',
    type: 'Beach',
    emoji: '🌊',
    bedrooms: 5,
    bathrooms: 3,
    sleepsMin: 10,
    sleepsMax: 16,
    pricePerNight: 1751,
    description: 'White-sand beaches, turquoise waters, and fiery sunsets await when you stay at this stunning 5-bedroom, 3-bathroom vacation rental in Clearwater. The home greets guests with a sleek interior packed with modern decor and high-end amenities. Easily host family gatherings between the kitchen, dining areas, and living room thanks to the breezy open floor plan.',
    shortDesc: 'White-sand beaches, turquoise waters & fiery sunsets. Private pool, steps from Pier 60.',
    amenities: ['Private Pool', 'Pet Friendly', 'WiFi', 'Near Ocean', 'Modern Kitchen', 'Outdoor Dining'],
    imageUrl: 'https://uc.orez.io/i/d9fccbcf4d134005b4a23f9add34764f-Medium',
    ownerrezUrl: 'https://www.fabvacayvibes.com/casa-grand%c3%a8-orp5b613a7x',
    highlights: ['Walk to Pier 60', 'Clearwater Marine Aquarium nearby', 'BayCare Ballpark — Spring Training'],
    photos: [
    '/images/casa-grande/01-001_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/02-002_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/03-005_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/04-006_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/05-003_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/06-004_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/07-007_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/08-008_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/09-009_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/10-010_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/11-011_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/12-012_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/13-013_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/14-014_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/15-015_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/16-016_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/17-017_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/18-018_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/19-019_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/20-020_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/21-021_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/22-022_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/23-023_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/24-024_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/25-025_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/26-026_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/27-027_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/28-028_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/29-029_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/30-030_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/31-031_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/32-032_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/33-033_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/34-034_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/35-035_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/36-036_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/37-037_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/38-038_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/39-039_18 Maywood Ave_by_Johnruzphoto.com.jpg',
    '/images/casa-grande/40-040_18 Maywood Ave_by_Johnruzphoto.com.jpg'
  ],
  },
  {
    id: 'owl-and-hare',
    slug: 'owl-and-hare',
    name: 'Owl & Hare',
    location: 'Joshua Tree',
    state: 'CA',
    type: 'Desert',
    emoji: '🏜️',
    bedrooms: 4,
    bathrooms: 4,
    sleepsMin: 7,
    sleepsMax: 10,
    pricePerNight: 3218,
    description: 'Owl & Hare is a 4-bed wellness retreat fitted with a pool, hot tub & vintage Airstream perched in the Joshua Tree Highlands overlooking the park entrance. Comprised of 2 stand-alone homes, the property is perfect for couples, families, or any group wanting to be together in a serene compound.',
    shortDesc: 'Wellness retreat in the Joshua Tree Highlands. Pool, hot tub & vintage Airstream with park views.',
    amenities: ['Private Pool', 'Hot Tub', 'Vintage Airstream', 'Pet Friendly', 'WiFi', 'Fire Pit', 'Mountain Views', 'Desert Views'],
    imageUrl: 'https://uc.orez.io/i/e52465e2ecfc4e90ac7a4d1cf90d6867-Medium',
    ownerrezUrl: 'https://www.fabvacayvibes.com/owl-hare-orp5b6e904x',
    highlights: ['5 min to Joshua Tree NP', '5 min to Downtown JT', "25 min to Pappy & Harriet's"],
    photos: [
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--36.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--37.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-4.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-7.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3688.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3699.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3722.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3735.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3738.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3771.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3829.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3849.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3869.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3885.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3899.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3943.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3947.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4006.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4017.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4022.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4084.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4094.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4138.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4168.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4177.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4184.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4207.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4227.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4242.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4253.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4284.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4292.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4295.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4421.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4448.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4480.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4506.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4513.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4547.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4574.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4589.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4594.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4604.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4713.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4783.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4796.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4808.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4856.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4863.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4867.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4879.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4907.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4935.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4981.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4984.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4987.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5166.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5196.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5282.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5293.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5296.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5306.jpg',
    '/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5314.jpg'
  ],
  },
  {
    id: 'sierra-crest-haven',
    slug: 'sierra-crest-haven',
    name: 'Sierra Crest Haven',
    location: 'Oakhurst',
    state: 'CA',
    type: 'Mountain',
    emoji: '🏔️',
    bedrooms: 7,
    bathrooms: 3,
    sleepsMin: 12,
    sleepsMax: 16,
    pricePerNight: 4075,
    description: "Nestled on a premier ridge in Oakhurst, Sierra Crest Haven is a sprawling 4,700 sq. ft. private estate designed for those who seek both adventure and absolute relaxation. This 7-bedroom home offers a rare 'dual-view' experience: start your morning watching the sunrise over the high Sierra peaks and end your day with the sunset over the valley.",
    shortDesc: '4,700 sq ft mountain estate on a premier ridge. Dual sunrise & sunset views over the High Sierra.',
    amenities: ['Hot Tub', 'Fireplace', 'Mountain Views', 'Forest Setting', 'WiFi', 'Accessible', 'Multiple Living Areas'],
    imageUrl: 'https://uc.orez.io/i/7975782670be426bbcb386e4d1a002f6-Medium',
    ownerrezUrl: 'https://www.fabvacayvibes.com/sierra-crest-haven-orp5b74fbax',
    highlights: ['Dual sunrise & sunset views', 'Near Yosemite', '4,700 sq ft estate'],
    photos: [
    '/images/sierra-crest-haven/BAR/Bar_001.jpg',
    '/images/sierra-crest-haven/BAR/Bar_002.jpg',
    '/images/sierra-crest-haven/BAR/Bar_003.jpg',
    '/images/sierra-crest-haven/BAR/Bar_004.jpg',
    '/images/sierra-crest-haven/BAR/Bar_005.jpg',
    '/images/sierra-crest-haven/BAR/Bar_006.jpg',
    '/images/sierra-crest-haven/BAR/Bar_007.jpg',
    '/images/sierra-crest-haven/BAR/Bar_008.jpg',
    '/images/sierra-crest-haven/BAR/Bar_009.jpg',
    '/images/sierra-crest-haven/BAR/Bar_010.jpg',
    '/images/sierra-crest-haven/BAR/Bar_011.jpg',
    '/images/sierra-crest-haven/BAR/Bar_012.jpg',
    '/images/sierra-crest-haven/BAR/Bar_013.jpg',
    '/images/sierra-crest-haven/BAR/Bar_014.jpg',
    '/images/sierra-crest-haven/BAR/Bar_015.jpg',
    '/images/sierra-crest-haven/BAR/Bar_016.jpg',
    '/images/sierra-crest-haven/BAR/Bar_017.jpg',
    '/images/sierra-crest-haven/BAR/Bar_018.jpg',
    '/images/sierra-crest-haven/BAR/Bar_019.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_001.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_002.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_003.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_004.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_005.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_006.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_007.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_008.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_009.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_010.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_011.jpg',
    '/images/sierra-crest-haven/BATHROOM 1/Bathroom1_012.jpg',
    '/images/sierra-crest-haven/BATHROOM 2/Bathroom2_001.jpg',
    '/images/sierra-crest-haven/BATHROOM 2/Bathroom2_002.jpg',
    '/images/sierra-crest-haven/BATHROOM 2/Bathroom2_003.jpg',
    '/images/sierra-crest-haven/BATHROOM 2/Bathroom2_004.jpg',
    '/images/sierra-crest-haven/BATHROOM 2/Bathroom2_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_002.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_006.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_007.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_008.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_009.jpg',
    '/images/sierra-crest-haven/BEDROOM 1/Bedroom1_010.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_002.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_006.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_007.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_008.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_009.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_010.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_011.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_012.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_013.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_014.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_015.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_016.jpg',
    '/images/sierra-crest-haven/BEDROOM 2/Bedroom2_017.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_006.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_007.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_008.jpg',
    '/images/sierra-crest-haven/BEDROOM 3/Bedroom3_009.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_002.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_006.jpg',
    '/images/sierra-crest-haven/BEDROOM 4/Bedroom4_007.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_002.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_005.jpg',
    '/images/sierra-crest-haven/BEDROOM 5/Bedroom5_006.jpg',
    '/images/sierra-crest-haven/BEDROOM 6/Bedroom6_001.jpg',
    '/images/sierra-crest-haven/BEDROOM 6/Bedroom6_002.jpg',
    '/images/sierra-crest-haven/BEDROOM 6/Bedroom6_003.jpg',
    '/images/sierra-crest-haven/BEDROOM 6/Bedroom6_004.jpg',
    '/images/sierra-crest-haven/BEDROOM 6/Bedroom6_005.jpg',
    '/images/sierra-crest-haven/DRONE/Drone001.jpg',
    '/images/sierra-crest-haven/DRONE/Drone002.jpg',
    '/images/sierra-crest-haven/DRONE/Drone003.jpg',
    '/images/sierra-crest-haven/DRONE/Drone004.jpg',
    '/images/sierra-crest-haven/DRONE/Drone005.jpg',
    '/images/sierra-crest-haven/DRONE/Drone006.jpg',
    '/images/sierra-crest-haven/DRONE/Drone007.jpg',
    '/images/sierra-crest-haven/DRONE/Drone008.jpg',
    '/images/sierra-crest-haven/DRONE/Drone009.jpg',
    '/images/sierra-crest-haven/DRONE/Drone010.jpg',
    '/images/sierra-crest-haven/DRONE/Drone011.jpg',
    '/images/sierra-crest-haven/DRONE/Drone012.jpg',
    '/images/sierra-crest-haven/DRONE/Drone013.jpg',
    '/images/sierra-crest-haven/DRONE/Drone014.jpg',
    '/images/sierra-crest-haven/DRONE/Drone015.jpg',
    '/images/sierra-crest-haven/DRONE/Drone016.jpg',
    '/images/sierra-crest-haven/DRONE/Drone017.jpg',
    '/images/sierra-crest-haven/DRONE/Drone018.jpg',
    '/images/sierra-crest-haven/DRONE/Drone019.jpg',
    '/images/sierra-crest-haven/DRONE/Drone020.jpg',
    '/images/sierra-crest-haven/DRONE/Drone021.jpg',
    '/images/sierra-crest-haven/DRONE/Drone022.jpg',
    '/images/sierra-crest-haven/DRONE/Drone023.jpg',
    '/images/sierra-crest-haven/DRONE/Drone024.jpg',
    '/images/sierra-crest-haven/DRONE/Drone025.jpg',
    '/images/sierra-crest-haven/DRONE/Drone026.jpg',
    '/images/sierra-crest-haven/DRONE/Drone027.jpg',
    '/images/sierra-crest-haven/DRONE/Drone028.jpg',
    '/images/sierra-crest-haven/DRONE/Drone029.jpg',
    '/images/sierra-crest-haven/DRONE/Drone030.jpg',
    '/images/sierra-crest-haven/DRONE/Drone031.jpg',
    '/images/sierra-crest-haven/DRONE/Drone032.jpg',
    '/images/sierra-crest-haven/DRONE/Drone033.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_001.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_002.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_003.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_004.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_005.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_006.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_007.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_008.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_009.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_010.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_011.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_012.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_013.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_014.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_015.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_016.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_017.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_018.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_019.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_020.jpg',
    '/images/sierra-crest-haven/GAME ROOM/Gameroom_021.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_001.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_002.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_003.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_004.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_005.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_006.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_007.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_008.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_009.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_010.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_011.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_012.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_013.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_014.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_015.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_016.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_017.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_018.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_019.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_020.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_021.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_022.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_023.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_024.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_025.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_026.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_027.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_028.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_029.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_030.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_031.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_032.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_034.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_035.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_036.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_037.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_038.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_039.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_040.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_041.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_042.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_043.jpg',
    '/images/sierra-crest-haven/KITCHEN + DINING/DiningKitchen_044.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_001.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_002.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_003.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_004.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_005.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_006.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_007.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_008.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_009.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_010.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_011.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_012.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_013.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_014.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_015.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_016.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_017.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_018.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_019.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_020.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_021.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_022.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_023.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_024.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_025.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_026.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_027.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_028.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_029.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_030.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_031.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_032.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_033.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_034.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_035.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_036.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_037.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_038.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_039.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_040.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_041.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_042.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_043.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_044.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_045.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_046.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_047.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_048.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_049.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_050.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_051.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_054.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_055.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_056.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_057.jpg',
    '/images/sierra-crest-haven/LIFESTYLE/Lifestyle_058.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_001.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_005.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_006.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_008.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_015.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_017.jpg',
    '/images/sierra-crest-haven/LIVING ROOM/Livingroom_026.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_001.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_002.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_003.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_004.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_005.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_006.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_007.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_008.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_009.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_010.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_011.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_012.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_013.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_014.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_015.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_016.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_017.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_018.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_019.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_020.jpg',
    '/images/sierra-crest-haven/MASTER BATHROOM/Masterbath_021.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_001.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_002.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_003.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_004.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_005.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_006.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_007.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_008.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_009.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_010.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_011.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_012.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_013.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_014.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_015.jpg',
    '/images/sierra-crest-haven/MASTER BEDROOM/Masterbed_016.jpg'
  ],
  },
]
