export interface Property {
  id: string
  slug: string
  name: string
  location: string
  state: string
  type: 'Beach' | 'Desert' | 'Mountain'
  emoji: string
  bedrooms: number
  bathrooms: number
  sleepsMin: number
  sleepsMax: number
  pricePerNight: number
  description: string
  shortDesc: string
  amenities: string[]
  imageUrl: string
  ownerrezUrl: string
  highlights: string[]
  photos: string[]
}

export const properties: Property[] = [
  {
    id: 'casa-grande',
    slug: 'casa-grande',
    name: 'Casa Grandè',
    location: 'Clearwater',
    state: 'FL',
    type: 'Beach',
    emoji: '🌊',
    bedrooms: 5,
    bathrooms: 3,
    sleepsMin: 10,
    sleepsMax: 16,
    pricePerNight: 356,
    description: 'White-sand beaches, turquoise waters, and fiery sunsets await when you stay at this stunning 5-bedroom, 3-bathroom vacation rental in Clearwater. The home greets guests with a sleek interior packed with modern decor and high-end amenities. Easily host family gatherings between the kitchen, dining areas, and living room thanks to the breezy open floor plan.',
    shortDesc: 'White-sand beaches, turquoise waters & fiery sunsets. Private pool, steps from Pier 60.',
    amenities: ['Private Pool', 'Pet Friendly', 'WiFi', 'Near Ocean', 'Modern Kitchen', 'Outdoor Dining'],
    imageUrl: 'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/01-001_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    ownerrezUrl: 'https://www.fabvacayvibes.com/casa-grand%c3%a8-orp5b613a7x',
    highlights: ['Walk to Pier 60', 'Clearwater Marine Aquarium nearby', 'BayCare Ballpark — Spring Training'],
    photos: [
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/38-038_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/39-039_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/40-040_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/04-006_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/08-008_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/09-009_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/10-010_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/11-011_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/12-012_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/13-013_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/14-014_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/15-015_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/16-016_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/17-017_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/18-018_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/19-019_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/20-020_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/21-021_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/22-022_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/23-023_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/24-024_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/25-025_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/26-026_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/27-027_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/28-028_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/29-029_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/31-031_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/32-032_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/33-033_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/34-034_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/35-035_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/30-030_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/36-036_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/37-037_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/03-005_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/06-004_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/05-003_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/07-007_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/02-002_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/casa-grande/01-001_18%20Maywood%20Ave_by_Johnruzphoto.com.jpg',
  ],
  },
  {
    id: 'owl-and-hare',
    slug: 'owl-and-hare',
    name: 'Owl & Hare',
    location: 'Joshua Tree',
    state: 'CA',
    type: 'Desert',
    emoji: '🏜️',
    bedrooms: 4,
    bathrooms: 4,
    sleepsMin: 7,
    sleepsMax: 10,
    pricePerNight: 500,
    description: 'Owl & Hare is a 4-bed wellness retreat fitted with a pool, hot tub & vintage Airstream perched in the Joshua Tree Highlands overlooking the park entrance. Comprised of 2 stand-alone homes, the property is perfect for couples, families, or any group wanting to be together in a serene compound.',
    shortDesc: 'Wellness retreat in the Joshua Tree Highlands. Pool, hot tub & vintage Airstream with park views.',
    amenities: ['Private Pool', 'Hot Tub', 'Vintage Airstream', 'Pet Friendly', 'WiFi', 'Fire Pit', 'Mountain Views', 'Desert Views'],
    imageUrl: 'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-.jpg',
    ownerrezUrl: 'https://www.fabvacayvibes.com/owl-hare-orp5b6e904x',
    highlights: ['5 min to Joshua Tree NP', '5 min to Downtown JT', "25 min to Pappy & Harriet's"],
    photos: [
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--10.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--11.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--12.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--13.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--14.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--15.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--16.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--17.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--18.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--19.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--2.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--20.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--21.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--22.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--23.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--24.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--25.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--26.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--27.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--28.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--29.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--3.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--30.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--31.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--32.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--33.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--34.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--35.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--36.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--37.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--38.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--39.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--4.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--40.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--41.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--42.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--43.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--44.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--45.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--46.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--47.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--48.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--49.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--5.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--50.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--51.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--52.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--53.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--54.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--55.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--56.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--57.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--58.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--59.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--6.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--60.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--61.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--62.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--63.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--64.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--65.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--66.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--7.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--8.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25--9.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-2.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-3.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-4.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-5.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-6.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-7.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2-8.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-2.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3217.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3225.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3233.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3241.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3243.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3247.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3253.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3258.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3262.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3266.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3269.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3272.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3276.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3287.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3289.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3293.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3296.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3299.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3303.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3305.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3306.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3317.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3321.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3325.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3328.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3331.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3332.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3336.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3340.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3343.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3346.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3349.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3683.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3688.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3699.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3722.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3735.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3738.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3771.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3774.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3776.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3829.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3849.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3869.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3885.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3899.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3943.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-3947.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4022.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4084.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4094.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4138.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4168.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4177.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4184.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4207.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4227.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4242.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4253.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4284.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4292.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4295.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4320.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4334.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4340.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4358.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4371.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4379.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4383.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4387.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4393.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4398.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4401.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4405.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4407.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4411.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4421.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4448.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4480.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4506.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4513.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4547.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4574.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4589.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4594.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4604.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4614.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4629.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4632.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4637.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4713.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4783.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4796.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4808.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4856.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4863.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4867.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4879.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4889.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4907.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4935.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4981.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4984.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-4987.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5166.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5196.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5282.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5293.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5296.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5306.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5314.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5329.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5332.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5336.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5340.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5356.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5362.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5365.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5367.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5369.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5372.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5376.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5383.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5389.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5395.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5400.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5404.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5410.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5457.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5517.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5519.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5523.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5528.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5531.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5534.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/owl-and-hare/8283ViaRecosaJoshuaTreeCa4_3_25-5546.jpg',
  ],
  },
  {
    id: 'sierra-crest-haven',
    slug: 'sierra-crest-haven',
    name: 'Sierra Crest Haven',
    location: 'Oakhurst',
    state: 'CA',
    type: 'Mountain',
    emoji: '🏔️',
    bedrooms: 7,
    bathrooms: 3,
    sleepsMin: 12,
    sleepsMax: 16,
    pricePerNight: 945,
    description: "Nestled on a premier ridge in Oakhurst, Sierra Crest Haven is a sprawling 4,700 sq. ft. private estate designed for those who seek both adventure and absolute relaxation. This 7-bedroom home offers a rare 'dual-view' experience: start your morning watching the sunrise over the high Sierra peaks and end your day with the sunset over the valley.",
    shortDesc: '4,700 sq ft mountain estate on a premier ridge. Dual sunrise & sunset views over the High Sierra.',
    amenities: ['Hot Tub', 'Fireplace', 'Mountain Views', 'Forest Setting', 'WiFi', 'Accessible', 'Multiple Living Areas'],
    imageUrl: 'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone001.jpg',
    ownerrezUrl: 'https://www.fabvacayvibes.com/sierra-crest-haven-orp5b74fbax',
    highlights: ['Dual sunrise & sunset views', 'Near Yosemite', '4,700 sq ft estate'],
    photos: [
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone021.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone022.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone023.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone024.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone025.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone026.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone027.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone028.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone029.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone030.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone031.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone032.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/DRONE/Drone033.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIVING%20ROOM/Livingroom_026.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_021.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_022.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_023.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_024.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_025.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_026.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_027.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_028.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_029.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_030.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_031.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_032.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_034.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_035.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_036.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_037.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_038.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_039.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_040.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_041.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_042.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_043.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/KITCHEN%20+%20DINING/DiningKitchen_044.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BEDROOM/Masterbed_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/MASTER%20BATHROOM/Masterbath_021.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/GAME%20ROOM/Gameroom_021.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BAR/Bar_019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%201/Bedroom1_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%202/Bedroom2_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%203/Bedroom3_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%204/Bedroom4_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%205/Bedroom5_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%206/Bedroom6_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%206/Bedroom6_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%206/Bedroom6_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%206/Bedroom6_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BEDROOM%206/Bedroom6_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%201/Bathroom1_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%202/Bathroom2_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%202/Bathroom2_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%202/Bathroom2_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%202/Bathroom2_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/BATHROOM%202/Bathroom2_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_001.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_002.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_003.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_004.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_005.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_006.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_007.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_008.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_009.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_010.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_011.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_012.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_013.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_014.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_015.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_016.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_017.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_018.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_019.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_020.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_021.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_022.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_023.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_024.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_025.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_026.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_027.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_028.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_029.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_030.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_031.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_032.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_033.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_034.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_035.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_036.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_037.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_038.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_039.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_040.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_041.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_042.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_043.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_044.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_045.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_046.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_047.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_048.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_049.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_050.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_051.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_054.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_055.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_056.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_057.jpg',
    'https://ffxdvjgwnh5dbwtv.public.blob.vercel-storage.com/images/sierra-crest-haven/LIFESTYLE/Lifestyle_058.jpg',
  ],
  },
]
